### ISSUE TITLE
Surge previews are not working

### ISSUE THREAD

**Issue by jaydrogers** [postalserver/docs#14]
# Problem
Surge previews are no longer building. The Github Action is failing with the error message of
```
Error: Resource not accessible by integration
```

#### Example
https://github.com/postalserver/docs/pull/13/checks?check_run_id=3827495234#step:3:13

# Impact
* It does not really impact Postal users -- the docs still build just fine
* It just might help speed up PR requests since we can see a test site easily through surge

# Possible Cause
Github has an explanation on their blog: https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/

# Moving forward
* I was going to investigate this myself, but I no longer have access to the repository settings
* I forget which secrets we had set on the repo (if any)

Let me know if you have any thoughts or ideas!

**Comment by willpower232** [comment]
Interesting that the command apparently succeeded in that the URL is still working https://postalserver-docs-preview-pr-13.surge.sh

**Comment by jaydrogers** [comment]
Seems to be fixed by https://github.com/postalserver/docs/pull/37 🥳
