### ISSUE TITLE
auto start not working

### ISSUE THREAD

**Issue by nisamudeen97** [postalserver/docs#15]
Hi,

When the entire server is rebooted.   Postal service is not coming UP automatic even if the containers are UP and running. 
![Screenshot from 2021-11-22 12-46-58](https://user-images.githubusercontent.com/12267398/142819427-d79164c4-38ef-4555-941d-3c03fd8f3078.png)

We have to manually start using the command "postal start".  Is it possible to enable autostart?

**Comment by jaydrogers** [comment]
This repo is for the docs only. Your request is for user support, which needs to be held on the "Discussions" area of the main Github repo.

Please open your question there: https://github.com/postalserver/postal/discussions

Also, just a heads up. You are using an unsupported version of Postal, so you'll need to upgrade your version before receiving support. See this for more detail: https://github.com/postalserver/postal/discussions/1513

**Comment by willpower232** [comment]
To clarify, it looks like dockerised Postal v2 is in use which implies everything should be auto starting but you'll have to check the logs to see what has failed and caused the container to not start.

**Comment by jaydrogers** [comment]
Whoops! I was flying through my inbox and saw the "postal start" and thought it was the old version. 😆

Correct, please check Docker logs and post under "Discussions" if you need further help.
