### ISSUE TITLE
Link to "Edit this page on GitHub" goes to the wrong URL

### ISSUE THREAD

**Issue by adamcooke** [postalserver/docs#2]
It seems to think all the docs are in a folder called `docs` whereas we have them in the root.

**Comment by willpower232** [comment]
Looks like we need to specify `defaultDir` in the config? https://content.nuxtjs.org/themes/docs#properties

I think this is a problem in your other site too @jaydrogers

**Comment by jaydrogers** [comment]
Thanks for pointing that out!

Out on holiday right now, but I will get this fixed when I return on Monday 👍

**Comment by adamcooke** [comment]
I sorted this earlier :)
