### ISSUE TITLE
Missing dokumentation for frontend settings

### ISSUE THREAD

**Issue by samip5** [postalserver/docs#23]
I could not find any information as to how and/if I can set the smtp settings for frontend to use something else than just PLAIN auth.

**Comment by willpower232** [comment]
You can see in the code that Postal supports `AUTH CRAM-MD5 PLAIN LOGIN`

https://github.com/postalserver/postal/blob/main/lib/postal/smtp_server/client.rb

Feel free to start a discussion in the main repo if you need more clarification.
