### ISSUE TITLE
The TLS/SSL certificate does not support

### ISSUE THREAD

**Issue by JanesDev** [postalserver/docs#25]
After installing and configuring postal, I wanted to send an email through the ultramailer application using a secure connection, but this did not work and I was made to understand that the server does not accept secure connections. so after research, I saw that we were asking to generate an ssl certificate for the domain which I have and that the following lines had to be added to the postal configuration file:
  tls_enabled: true;
  tls_certificate_path: /etc/letsencrypt/live/postal.example.com/fullchain.pem;
  tls_private_key_path: /etc/letsencrypt/live/postal.example.com/privkey.pem;
and now the server no longer shows me the same error but it shows me this:
SMTP send error
Failure sending mail.
Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by willpower232** [comment]
It sounds like you need to provide the certificate files to Postal which is slightly more of a challenge now the configuration is provided through a docker-compose.yml file.

Have a look in the discussions in the main repository [postalserver/postal](https://github.com/postalserver/postal) and open a discussion there if you continue to have problems.
