### ISSUE TITLE
Backup Documentation

### ISSUE THREAD

**Issue by i5hi** [postalserver/docs#31]
Not able to find docs on backups.

Is there a standard process to backup and recover a postal installation and data?

**Comment by willpower232** [comment]
All of Postals data is stored in a series of MySQL databases so you would need to take backups of all those databases (or the entire database server) and restore that.

Certainly a challenging topic to fully and clearly document but at least its all in one place.

**Comment by i5hi** [comment]
Awesome Thanks!
