### ISSUE TITLE
after installion error on make user

### ISSUE THREAD

**Issue by githubsharezone** [postalserver/docs#34]
after installrion i recevie

exec /docker-entrypoint.sh: exec format error
root@armdkr02:/opt/postal/config# postal make-user administrator@sharezone.cloud

**Comment by willpower232** [comment]
this is not a docs issue, please open a discussion in [postalserver/postal](https://github.com/postalserver/postal)

it would be good to know if you have made your own docker image or have other non postal docker things running.
