### ISSUE TITLE
Error to postal initialize

### ISSUE THREAD

**Issue by rafaellfmachado** [postalserver/docs#38]
oot@postal:/# postal initialize
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Comment by willpower232** [comment]
This isn't a documentation problem, please can you open an issue in the main repository https://github.com/postalserver/postal
