### ISSUE TITLE
Bounce Failover to another instance...

### ISSUE THREAD

**Issue by tpnsolutions** [postalserver/docs#39]
I'd like to setup Postal so that when "certain" bounces are caught, a message could be attempted via different node until X amount of attempts have been made.

Ex. ISP bounces or blocks due to "high volume" from an IP address (false positive), and we have 3 nodes connected to the same Postal database and queue... The failed message could then be attempted 2 more times from each of 2 other nodes until success or ultimately complete failure.

*** We only have "one" IP address per node ***

With the above concept, I'd still want to receive a webhook so I'm aware of the problem and can address it accordingly, but it'd be nice to at least try sending "certain" messages (based on criteria) from another node that might succeed.

Obviously if the message is being bounced for reasons like "user does not exist", or legit "spam complaint" then I'd want to halt another attempt, however a large portion of mail going outbound is blocked or bounced simply because of the volume of email being sent from the same server in a short period of time (which is why we have multiple nodes to deal with this) -- we run a mailing list service so for instance we may have 20 clients send out mail at or around the same time to say 5,000 subscribers each which cause a false positive with select ISPs due to the sudden email burst.

**Comment by willpower232** [comment]
This is not a documentation issue, please open a discussion in the main repository https://github.com/postalserver/postal
