### ISSUE TITLE
mail forwarding http routing endpoint issue

### ISSUE THREAD

**Issue by andrewudxgen** [postalserver/docs#44]
hello,

we're routing all mails to http end point using routing module, it was working fine before.
now all the mail are forwarding to queue with status **PENDING**. we have attach the screens as reference.

when we try redeliver message button, it shows **"this message will be retried shortly"**

it works if we stop & start postal server from console.

thanks in advance!!!

![image](https://github.com/postalserver/docs/assets/40357654/39f3f5ab-d1a8-4351-8e14-edbb16ec5285)

![image](https://github.com/postalserver/docs/assets/40357654/991cc7c6-b1a6-4c6f-8699-7d6688edf416)

**Comment by willpower232** [comment]
This is not a docs problem, please open a discussion in the main repository https://github.com/postalserver/postal
