### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by hendrik-brower** [postalserver/docs#45]
Just following along the installation instructions, failed at postal initialize.
Looks like docker packages the compose as part of docker and the command line
might need to change from:

docker-compose ...

to 

docker compose ...

I just made a quick shortcut:
#!/bin/bash
docker compose "$@"

seems to work, so suspect its a trivial update to initialize

**Comment by willpower232** [comment]
this is not a documentation issue. Have a look at https://github.com/postalserver/install/pull/8
