### ISSUE TITLE
prerequisites page: Linode and Digitalocean block port 25 by default

### ISSUE THREAD

**Issue by onokje** [postalserver/docs#46]
This page: /install/prerequisites

It seems that both Linode and Digitalocean now block port 25 by default, pretty much making it impossible to use postal on these. Any tips on where to run my own postal server?

**Comment by KalynDavis** [comment]
You should be able to request those ports to be opened. I'm using Vultr and was able to request port 25 to be opened. I did have to supply my use and intentions for the port.

**Comment by willpower232** [comment]
This is definitely more of a research task for yourself, if the ports are blocked by default then there will be some mechanism for them to be opened or other provider available.

They are just examples of cloud VPS providers, don't really want to become a directory of server providers.
