### ISSUE TITLE
Authentication required after update to 2.1.4

### ISSUE THREAD

**Issue by Trapulo** [postalserver/docs#47]
Hi,
I've just upgraded from 2.1.2 to 2.1.4 and I have a problem with SMTP-IP authentication. 
I've an authorization based on my IP subnet that did work until the upgrade. Now, when I perform the anonymous SMTP session to submit a message, the server respond "530 Authentication required" and does not accept an anonymous session.

Is this a bug? Or.. ?
thanks

**Comment by willpower232** [comment]
Not a docs issue, please open a discussion in the main postal repo
