### ISSUE TITLE
Setting Up an Avatar for My Email Address

### ISSUE THREAD

**Issue by mihailbishkek** [postalserver/docs#48]
I hope this message finds you well. I am writing to inquire about setting up an avatar or profile picture for my email address, especially for the emails I send out. This would help in personalizing my emails and making them easily recognizable to the recipients.

Could you please guide me through the process or provide any relevant documentation or resources that I can refer to? Your assistance would be greatly appreciated.

Thank you in advance for your time and help. I look forward to your response.

**Comment by willpower232** [comment]
This isn't a docs issue and isn't a Postal feature I am afraid.

You may be able to set up an account on gravatar.com which would cover some places but it depends entirely on what email programs are being used to read emails you send.
