### ISSUE TITLE
node:16 is "End of Life"

### ISSUE THREAD

**Issue by bluepuma77** [postalserver/docs#49]
Even though [just changed](https://github.com/postalserver/docs/blob/main/docker-compose.yml), node:16 is already "[End of Life](https://nodejs.dev/en/about/releases/)" (2023-09-11)

**Comment by jaydrogers** [comment]
Yup. The change is for compatibility reasons. When we upgrade to Nuxt Content V2, it will take care of the Node version: https://content.nuxtjs.org/blog/announcing-v2
