### ISSUE TITLE
I am tired: RabbitMQ authentication fails

### ISSUE THREAD

**Issue by LordAragornsLaptop** [postalserver/docs#52]
No special chars. The only thing which does not seem right was that "postal initialize" echoed database postal already exists. Whenever I try to send a test mail immediatly according to the logs the rabbitmq authentication fails and the workers never start again.

**Comment by willpower232** [comment]
Sorry you are tired but this isn't a docs issue.

You don't need to initialize more than once and it sounds like you, or someone, already did so it should be fine.

If your RabbitMQ is definitely working fine then you may be interested in https://github.com/postalserver/install/pull/3/files

If you're still having trouble, feel free to open a discussion in the main repository.

**Comment by LordAragornsLaptop** [comment]
Thank u a lot for helping dude. But I am the only one who us using the machine and I did not do postal initialise more than once, rather two complete new installs on new vpss. I don't understand why the hell it says db postal exists and why rabbitmq gets authentication fail when trying to send a test mail. I feel there is smth wrong with the docker containers or env vars on the website. 

Let me take this issue to the main branch.
