### ISSUE TITLE
worker rallying

### ISSUE THREAD

**Issue by brkcnbz** [postalserver/docs#54]
hi, Is there an example of this method?
(Docker only.)
![image](https://github.com/postalserver/docs/assets/77095940/c2398194-f651-4d5c-af7d-2ecf473433a2)

**Comment by willpower232** [comment]
If you are using docker-compose as per the standard installation, you can use the scale argument. https://github.com/postalserver/postal/discussions/1907#discussion-3939219

If you are using docker without docker-compose then I'm not sure you can scale horizontally easily.

If you aren't using docker, you will need to look at how what you are using scales horizontally.

**Comment by brkcnbz** [comment]
@willpower232  You're welcome for the guidance
