### ISSUE TITLE
Web container performance about

### ISSUE THREAD

**Issue by brkcnbz** [postalserver/docs#56]
I’m testing Postal on a 16-core, 16GB memory Ubuntu 22.04 Docker host. I can reduce the queue side by increasing the number of workers, but during this time the web container can’t handle the load and tracking URLs and such become inoperable. I’ve also made performance improvements on the MySQL side. Additionally, I’ve tried with webhook both open and closed, but the CPU on the web side becomes 100% and it becomes unresponsive. Is there a way to distribute the load here or increase performance on the web side?

Additionally, I receive mail requests via the API.

**Comment by willpower232** [comment]
This isn't a docs issue but you could juggle some ports to have a plural of web containers probably presuming you haven't added too many workers and still have some resources available.

Do open a discussion in the main Postal repo with whatever you find out next.
