### ISSUE TITLE
Add Drupal integration to Client Libraries?

### ISSUE THREAD

**Issue by petertornstrand** [postalserver/docs#73]
Since the [Drupal integration](https://www.drupal.org/project/postal_mail) is not strictly a library (makes use of the Postal PHP client library) but a way for Drupal sites to replace the core mail function with Postal I'm not sure if should be added to the Client Libraries doc page.

Perhaps there should be another doc page? _CMS Integrations_ or something like that?

**Comment by willpower232** [comment]
If it is available via composer then that sounds like a library to me, albeit quite niche as technically it relies on drupal. Feel free to open a PR.

As an aside and out of genuine curiosity, I don't know how drupal development works, technically should you add some drupal components in composer json so it can't be used without drupal? Also would you publish it on packagist or isn't that supported by where you keep the code?

**Comment by petertornstrand** [comment]
Ok, I will do that.

Regarding Drupal. The code can't really be used without Drupal (as you wrote) and the Drupal contrib module *Mail System*. That dependency is specified in the `postal_mail.info.yml` file. I guess I could add a composer dependency on Drupal core but that is not standard for Drupal modules as this is also specified in the `.info.yml` file for the module.

The module is distributed via Drupals own composer repository available at https://packages.drupal.org/8

You could publish it on Packagist as long as your `composer.json` file specifies `"type": "drupal-module"`.

**Comment by willpower232** [comment]
Ah good to know, thanks for saying.
